MODEL:
    FIX2D: True
    # PRETRAIN: "/usr/src/app/panoptic-reconstruction/data/panoptic-front3d.pth"
    # PRETRAIN: "/usr/src/app/panoptic-reconstruction/output/02_2022-06-2910_18_19.152368/model_final.pth"
    PRETRAIN: "/usr/src/app/panoptic-reconstruction/output/04_2022-07-0412_02_00.574182/model_final.pth"

    ONLY_PANOPTIC_PRETRAINED: False

    FIXNORM: True

    DEPTH2D:
        USE: True
        FIX: True

    INSTANCE2D:
        USE: True
        FIX: True

    PROJECTION:
        USE: True
        SIGN_CHANNEL: True

    FRUSTUM3D:
        USE: True
        FIX: False
        TRUNCATION: 3.0
        ISO_VALUE: 1.0
        IS_SDF: False

        SEMANTIC_WEIGHT: 5.0
        INSTANCE_WEIGHT: 25.0
        COMPLETION_WEIGHT: 50.0
        COMPLETION_128_WEIGHT: 25.0
        COMPLETION_256_WEIGHT: 10.0
        L1_WEIGHT: 5.0
        RGB_WEIGHT: 50.0

 
        LEVEL_ITERATIONS_64: 500 # 10000
        LEVEL_ITERATIONS_128: 1250 # 25000
        LEVEL_ITERATIONS_256: 2500 #5000
        LEVEL_ITERATIONS_RGB: 2500 #5000  #TO DO: Implement. Right now it is unused


        COMPLETION_VOXEL_WEIGHTING: True
        COMPLETION_128_VOXEL_WEIGHTING: True
        COMPLETION_256_VOXEL_WEIGHTING: True
        SURFACE_VOXEL_WEIGHTING: True

        SEMANTIC_VOXEL_WEIGHTING: False
        INSTANCE_VOXEL_WEIGHTING: False

DATASETS:
    TRAIN: "Front3D_Train"
    VAL: "Front3D_Validation"
    TRAINVAL: "Front3D_Train"
    TEST: "Front3D_Test"
    NUM_TRAIN: 0
    NUM_TEST: 100
    NUM_VALIDATE: 50
    OVERFITTING: False
    FIELDS: ("color", "depth", "instance2d", "geometry", "instance3d", "semantic3d", "aux_views")

DATALOADER:
    IMS_PER_BATCH: 1
    MAX_ITER: 6000 #300000
    SHUFFLE: True
    NUM_WORKERS: 1

SOLVER:
    BASE_LR: 0.0005
    BETA_1: 0.9
    BETA_2: 0.999
    STEPS: (3000, 4000) #(100000, 150000)
    CHECKPOINT_PERIOD: 2000 #5000
    WEIGHT_DECAY: 0.0000001
    EVALUATION_PERIOD: 2000 #50000
