MODEL:
    FIX2D: True
    PRETRAIN: "/usr/src/app/panoptic-reconstruction/data/panoptic-front3d.pth"
    # PRETRAIN: "/usr/src/app/panoptic-reconstruction/output/27_2022-07-1005_35_07.805685/model_0003000.pth"
    ONLY_PANOPTIC_PRETRAINED: True
    USE_PRETRAINED: False
    COLOR_SPACE: "RGB"
    DEVICE_ID: 0

    FIXNORM: True

    DEPTH2D:
        USE: True
        FIX: True

    INSTANCE2D:
        USE: True
        FIX: True

    PROJECTION:
        USE: True
        SIGN_CHANNEL: True

    FRUSTUM3D:
        USE: True
        FIX: False
        TRUNCATION: 3.0
        ISO_VALUE: 1.0
        IS_SDF: False
        NUM_VIEWS: 3
        ENHANCE_CONTRAST: True

        SEMANTIC_WEIGHT: 0.5
        INSTANCE_WEIGHT: 1.0
        COMPLETION_WEIGHT: 25.0
        COMPLETION_128_WEIGHT: 10.0
        COMPLETION_256_WEIGHT: 5.0
        L1_WEIGHT: 5.0
        L1_WEIGHT_64: 0.05
        L1_WEIGHT_128: 0.1
        RGB_WEIGHT: 50.0
        RGB_WEIGHT_64: 0.05
        RGB_WEIGHT_128: 0.1

        # RGB WEIGHTS
        RGB_L1_WEIGHT: 8.0
        STYLE_WEIGHT: 0.001
        CONTENT_WEIGHT: 0.001
        GEN_WEIGHT: 1.0
 
        LEVEL_ITERATIONS_64: 4000 # 10000
        LEVEL_ITERATIONS_128: 4000 # 25000
        LEVEL_ITERATIONS_256: 4000 #5000
        LEVEL_ITERATIONS_RGB: 4000 #5000  #TO DO: Implement. Right now it is unused


        COMPLETION_VOXEL_WEIGHTING: True
        COMPLETION_128_VOXEL_WEIGHTING: True
        COMPLETION_256_VOXEL_WEIGHTING: True
        SURFACE_VOXEL_WEIGHTING: True

        SEMANTIC_VOXEL_WEIGHTING: False
        INSTANCE_VOXEL_WEIGHTING: False

DATASETS:
    TRAIN: "Front3D_Train"
    VAL: "Front3D_Validation"
    TRAINVAL: "Front3D_TrainVal"
    TEST: "Front3D_Test"
    NUM_TRAIN: 0
    NUM_TEST: 100
    NUM_VALIDATE: 50
    OVERFITTING: False
    FIELDS: ("color", "depth", "instance2d", "geometry", "instance3d", "semantic3d", "aux_views")

DATALOADER:
    IMS_PER_BATCH: 1
    MAX_ITER: 300000 #300000
    SHUFFLE: True
    NUM_WORKERS: 6

SOLVER:
    BASE_LR: 0.0001
    BETA_1: 0.9
    BETA_2: 0.999
    STEPS: (100000, 150000) #(100000, 150000)
    CHECKPOINT_PERIOD: 5000 #5000
    WEIGHT_DECAY: 0.000001
    EVALUATION_PERIOD: 1000 #50000